# pull official base image
FROM python:3.10.12

# set work directory
WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt


# Copy static files to the appropriate location
COPY ./static /app/static

# copy project
COPY . /app/


CMD ["gunicorn", "--bind", "0.0.0.0:8000", "e_voting.wsgi:application"]

EXPOSE 8000