# Dockerfile for MySQL
FROM mysql:8.0.35

ENV MYSQL_ROOT_PASSWORD=Kobedropped81
ENV MYSQL_DATABASE=e_voting
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=Kobedropped81

COPY ./mysql-init.sql /docker-entrypoint-initdb.d/